import React, { useEffect, useState } from 'react';
import { supabase } from '../supabaseClient';
import { Comanda, ItemPedido, CaixaSessao, HistoricoItem, MovimentacaoCaixa } from '../types';
import { mapSupabaseError } from '../utils/errors';

function makeEmptyComandas(): Record<number, Comanda> { const c: Record<number, Comanda> = {}; for (let i=1;i<=100;i++) c[i]={id:i,status:'livre',items:[],mesa:'',garcom:'',obs:'',openedAt:null,discount:0}; return c; }
function isEmployeeSession(){ return Boolean(localStorage.getItem('servio_emp_token')); }
function mapRows(rows:any[]):Record<number,Comanda>{ const next=makeEmptyComandas(); for(const c of rows||[]){const n=Number(c.number);if(n<1||n>100)continue;next[n]={id:n,uuid:c.id,status:c.status==='aberta'?'aberta':'livre',items:(c.comanda_items||[]).map((it:any)=>({id:it.id,pid:it.product_id,name:it.name,price:Number(it.price),qty:Number(it.quantity),note:it.notes||''})),mesa:c.table_number||'',garcom:c.waiter_id||'',obs:c.notes||'',openedAt:c.opened_at?new Date(c.opened_at).getTime():null,discount:Number(c.discount||0)};}return next;}

export function useComandas(restaurantId:string,ownerName:string,caixaAtiva:CaixaSessao|null,setMovimentacoesCaixa:React.Dispatch<React.SetStateAction<MovimentacaoCaixa[]>>,setHistory:React.Dispatch<React.SetStateAction<HistoricoItem[]>>){
 const [comandas,setComandas]=useState<Record<number,Comanda>>(makeEmptyComandas());
 useEffect(()=>{if(!restaurantId){setComandas(makeEmptyComandas());return;}let cancelled=false;const employee=isEmployeeSession();
  const load=async()=>{if(cancelled)return;if(employee){const token=localStorage.getItem('servio_emp_token');if(!token)return;const {data,error}=await supabase.rpc('get_employee_context',{p_token:token});if(!error&&data&&!cancelled)setComandas(mapRows(Array.isArray(data.comandas)?data.comandas:[]));return;}
   const {data,error}=await supabase.from('comandas').select('*, comanda_items(*)').eq('restaurant_id',restaurantId).eq('status','aberta');if(!error&&!cancelled)setComandas(mapRows(data||[]));
  };
  load();const timer=employee?setInterval(load,1500):setInterval(load,2000);return()=>{cancelled=true;clearInterval(timer)};
 },[restaurantId]);

 const handleOpenComanda=async(id:number)=>{if(!restaurantId)return;
  if(isEmployeeSession()){const token=localStorage.getItem('servio_emp_token');if(!token)return;const {data,error}=await supabase.rpc('employee_open_comanda',{p_token:token,p_number:id});if(error){alert('Erro ao abrir comanda: '+error.message);return;}setComandas(prev=>({...prev,[id]:{...prev[id],id,uuid:data?.uuid,status:'aberta',openedAt:Number(data?.openedAt||Date.now()),mesa:data?.mesa||'',obs:data?.obs||'',discount:Number(data?.discount||0)}}));return;}
  const existing=comandas[id];if(existing?.uuid){const {data}=await supabase.from('comandas').select('id,status').eq('id',existing.uuid).maybeSingle();if(data?.status==='aberta')return;}
  const {data,error}=await supabase.from('comandas').insert({restaurant_id:restaurantId,number:id,status:'aberta',opened_at:new Date().toISOString()}).select().single();
  if(error){if(error.code==='23505'){const {data:db}=await supabase.from('comandas').select('id,status').eq('restaurant_id',restaurantId).eq('number',id).eq('status','aberta').maybeSingle();if(db){setComandas(prev=>({...prev,[id]:{...prev[id],uuid:db.id,status:'aberta',openedAt:Date.now()}}));return;}}console.error('[handleOpenComanda]',error);alert('Erro ao abrir comanda: '+mapSupabaseError(error));return;}
  setComandas(prev=>({...prev,[id]:{...prev[id],uuid:data.id,status:'aberta',openedAt:new Date(data.opened_at).getTime()}}));
 };

 const handleItemsUpdate=async(id:number,items:ItemPedido[],discount=0)=>{if(!restaurantId)return;const current=comandas[id];setComandas(prev=>({...prev,[id]:{...prev[id],items,discount,status:'aberta'}}));
  if(isEmployeeSession()){const token=localStorage.getItem('servio_emp_token');if(!token)return;const {data,error}=await supabase.rpc('employee_save_comanda',{p_token:token,p_number:id,p_items:items,p_discount:discount,p_mesa:current?.mesa||'',p_obs:current?.obs||''});if(error){console.error('[employee_save_comanda]',error);return;}setComandas(prev=>({...prev,[id]:{...prev[id],uuid:data?.uuid,status:'aberta'}}));return;}
  let uuid=current?.uuid;if(!uuid){const {data}=await supabase.from('comandas').select('id').eq('restaurant_id',restaurantId).eq('number',id).eq('status','aberta').maybeSingle();uuid=data?.id;if(!uuid){const {data:n,error}=await supabase.from('comandas').insert({restaurant_id:restaurantId,number:id,status:'aberta',opened_at:new Date().toISOString()}).select().single();if(error&&error.code==='23505'){const {data:db}=await supabase.from('comandas').select('id').eq('restaurant_id',restaurantId).eq('number',id).eq('status','aberta').maybeSingle();uuid=db?.id;}else uuid=n?.id;}}
  if(!uuid)return;const subtotal=items.reduce((s,it)=>s+it.price*it.qty,0),total=Math.max(0,subtotal-discount);await supabase.from('comanda_items').delete().eq('comanda_id',uuid);if(items.length)await supabase.from('comanda_items').insert(items.map(it=>({comanda_id:uuid,product_id:it.pid,name:it.name,price:it.price,quantity:it.qty,notes:it.note||null})));await supabase.from('comandas').update({discount,subtotal,total,updated_at:new Date().toISOString()}).eq('id',uuid);
 };
 const handleMetaUpdate=async(id:number,meta:{mesa:string;garcom:string;obs:string})=>{const current=comandas[id];setComandas(prev=>({...prev,[id]:{...prev[id],...meta}}));if(!restaurantId)return;if(isEmployeeSession()){const token=localStorage.getItem('servio_emp_token');if(!token)return;await supabase.rpc('employee_save_comanda',{p_token:token,p_number:id,p_items:current?.items||[],p_discount:current?.discount||0,p_mesa:meta.mesa,p_obs:meta.obs});return;}if(current?.uuid)await supabase.from('comandas').update({table_number:meta.mesa,notes:meta.obs,updated_at:new Date().toISOString()}).eq('id',current.uuid);};
 const handleConfirmPayment=async(id:number,method:string,_received?:number):Promise<boolean>=>{const current=comandas[id];if(!current||current.items.length===0||!restaurantId)return false;if(isEmployeeSession()){const token=localStorage.getItem('servio_emp_token');if(!token)return false;const {data,error}=await supabase.rpc('employee_close_comanda',{p_token:token,p_number:id,p_method:method});if(error||!data)return false;setComandas(prev=>({...prev,[id]:{id,status:'livre',items:[],mesa:'',garcom:'',obs:'',openedAt:null,discount:0}}));return true;}if(!current.uuid)return false;const subtotal=current.items.reduce((s,it)=>s+it.price*it.qty,0),total=Math.max(0,subtotal-(current.discount||0)),now=new Date().toISOString();const {error}=await supabase.from('comandas').update({status:'fechada',payment_method:method,subtotal,discount:current.discount||0,total,closed_at:now,updated_at:now}).eq('id',current.uuid);if(error){alert('Erro ao fechar comanda: '+error.message);return false}setComandas(prev=>({...prev,[id]:{id,status:'livre',items:[],mesa:'',garcom:'',obs:'',openedAt:null,discount:0}}));setHistory(prev=>[{id:current.uuid!,cmdId:id,mesa:current.mesa||'',garcom:current.garcom||'',obs:current.obs||'',items:current.items.map(it=>({...it})),subtotal,discount:current.discount||0,total,payMethod:method,openedAt:current.openedAt||Date.now(),closedAt:Date.now()},...prev]);return true;};
 const handleCloseEmptyComanda=(id:number)=>setComandas(prev=>({...prev,[id]:{...prev[id],status:'livre',openedAt:null}}));
 return {comandas,handleMetaUpdate,handleItemsUpdate,handleOpenComanda,handleConfirmPayment,handleCloseEmptyComanda,setComandas};
}