import React, { useState } from 'react';
import { Categoria, Produto } from '../types';
import ConfirmModal from './ConfirmModal';
import LucideIcon from './LucideIcon';
import { Plus, Edit2, Trash2, Tag, Search } from 'lucide-react';

interface CategoriasProps { categories: Categoria[]; products: Produto[]; onCreateCategory:(c:Omit<Categoria,'id'>)=>void; onUpdateCategory:(id:string,c:Partial<Categoria>)=>void; onDeleteCategory:(id:string)=>void; isEmployee?:boolean; }
export default function Categorias({categories,products,onCreateCategory,onUpdateCategory,onDeleteCategory,isEmployee=false}:CategoriasProps){
 const [search,setSearch]=useState(''); const [modal,setModal]=useState(false); const [editingId,setEditingId]=useState<string|null>(null); const [categoryToDelete,setCategoryToDelete]=useState<{id:string,count:number}|null>(null); const [name,setName]=useState(''); const [icon,setIcon]=useState('Utensils'); const [color,setColor]=useState('#3B82F6');
 const filtered=categories.filter(c=>!search.trim()||c.name.toLowerCase().includes(search.toLowerCase()));
 const openEdit=(c:Categoria)=>{setEditingId(c.id);setName(c.name);setIcon(c.icon);setColor(c.color);setModal(true)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!name.trim())return;if(editingId)onUpdateCategory(editingId,{name:name.trim(),icon,color});else onCreateCategory({name:name.trim(),icon,color});setModal(false)};
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center gap-3 bg-[var(--bg-card)] border border-[var(--border-color)] p-4 rounded-xl">{!isEmployee&&<button onClick={()=>{setEditingId(null);setName('');setIcon('Utensils');setColor('#3B82F6');setModal(true)}} className="btn btn-primary cursor-pointer"><Plus size={15}/><span>Nova Categoria</span></button>}<div className="relative w-full sm:w-64"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--text-muted)]" size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar categoria..." className="w-full bg-[var(--bg-base)] border border-[var(--border-color)] rounded-lg pl-9 pr-3 py-2 text-xs outline-none focus:border-sky-500"/></div></div>
  <div className="bg-[var(--bg-card)] border border-[var(--border-color)] rounded-xl overflow-hidden"><div className="hidden sm:block overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-[var(--border-color)]"><th className="py-3 px-4 text-xs text-[var(--text-muted)]">Categoria</th><th className="py-3 px-4 text-xs text-[var(--text-muted)]">Cor</th><th className="py-3 px-4 text-xs text-[var(--text-muted)]">Produtos</th>{!isEmployee&&<th className="py-3 px-4 text-xs text-[var(--text-muted)] text-right">Ações</th>}</tr></thead><tbody>{filtered.length===0?<tr><td colSpan={isEmployee?3:4} className="py-12 text-center text-[#484F58]"><Tag className="mx-auto mb-2" size={36}/><p>Nenhuma categoria cadastrada.</p></td></tr>:filtered.map(c=>{const count=products.filter(p=>p.cid===c.id).length;return <tr key={c.id} className="border-b border-[var(--bg-hover)]/50 hover:bg-[var(--bg-hover)]/25"><td className="py-3 px-4"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-lg flex items-center justify-center border" style={{color:c.color,backgroundColor:`${c.color}15`,borderColor:`${c.color}35`}}><LucideIcon name={c.icon} size={18}/></div><span className="font-bold">{c.name}</span></div></td><td className="py-3 px-4"><span className="font-mono text-xs text-[var(--text-muted)]">{c.color}</span></td><td className="py-3 px-4"><span className="inline-flex px-2.5 py-0.5 rounded-full border text-xs">{count} produto(s)</span></td>{!isEmployee&&<td className="py-3 px-4 text-right"><button onClick={()=>openEdit(c)} className="p-1.5 mr-1 rounded-md cursor-pointer"><Edit2 size={14}/></button><button onClick={()=>setCategoryToDelete({id:c.id,count})} className="p-1.5 text-red-400 rounded-md cursor-pointer"><Trash2 size={14}/></button></td>}</tr>})}</tbody></table></div><div className="sm:hidden p-3 space-y-2">{filtered.map(c=>{const count=products.filter(p=>p.cid===c.id).length;return <div key={c.id} className="flex items-center gap-3 p-3.5 bg-[var(--bg-base)] border border-[var(--border-color)] rounded-xl"><div className="w-11 h-11 rounded-xl flex items-center justify-center border" style={{color:c.color,backgroundColor:`${c.color}15`,borderColor:`${c.color}35`}}><LucideIcon name={c.icon} size={20}/></div><div className="flex-1 min-w-0"><p className="font-bold">{c.name}</p><p className="text-xs text-[var(--text-muted)] mt-0.5">{count} produto(s) · {c.color}</p></div>{!isEmployee&&<div className="flex gap-2"><button onClick={()=>openEdit(c)} className="p-2.5 rounded-xl bg-[var(--bg-hover)] cursor-pointer"><Edit2 size={16}/></button><button onClick={()=>setCategoryToDelete({id:c.id,count})} className="p-2.5 rounded-xl bg-red-500/10 text-red-400 cursor-pointer"><Trash2 size={16}/></button></div>}</div>})}</div></div>
  {!isEmployee&&modal&&<div className="fixed inset-0 bg-black/75 backdrop-blur-sm flex items-end sm:items-center justify-center sm:p-4 z-50"><div className="w-full sm:max-w-sm bg-[var(--bg-card)] border border-[var(--border-color)] rounded-xl p-5 space-y-4"><div className="flex justify-between"><h3 className="font-bold">{editingId?'Editar Categoria':'Nova Categoria'}</h3><button onClick={()=>setModal(false)}>✕</button></div><form onSubmit={submit} className="space-y-4"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nome da Categoria" className="w-full bg-[var(--bg-base)] border border-[var(--border-color)] rounded-lg px-3 py-2"/><input value={icon} onChange={e=>setIcon(e.target.value)} placeholder="Ícone" className="w-full bg-[var(--bg-base)] border border-[var(--border-color)] rounded-lg px-3 py-2"/><input type="color" value={color} onChange={e=>setColor(e.target.value)} className="h-10 w-full bg-[var(--bg-base)] border border-[var(--border-color)] rounded-lg"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setModal(false)} className="px-4 py-2">Cancelar</button><button type="submit" className="px-4 py-2 bg-sky-500 rounded-lg font-bold">{editingId?'Salvar':'Criar'}</button></div></form></div></div>}
  <ConfirmModal isOpen={categoryToDelete!==null} title="Excluir Categoria" message={categoryToDelete?.count?`Esta categoria contém ${categoryToDelete.count} produto(s). Excluir mesmo assim?`:'Deseja excluir esta categoria?'} confirmText="Excluir" onConfirm={()=>{if(categoryToDelete)onDeleteCategory(categoryToDelete.id);setCategoryToDelete(null)}} onCancel={()=>setCategoryToDelete(null)}/>
 </div>;
}